homeassistant:
  packages: !include_dir_named packages
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include includes/customize.yaml
  whitelist_external_dirs:
    - /config/tmp

# Enables the frontend
frontend:
  themes: !include includes/themes.yaml
# Enables configuration UI
config:

http:
  base_url: !secret base_url
  api_password: !secret api_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # ip_ban_enabled: True
  # login_attempts_threshold: 5

updater:
discovery:
history:
logbook:
sun:
hassio:
system_health:
map:
ffmpeg:
stream:



# includes
sensor: !include_dir_merge_list includes/sensor/
binary_sensor: !include_dir_merge_list includes/binary_sensor/
input_boolean: !include includes/input_boolean.yaml
switch: !include_dir_merge_list includes/switch/
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
alert: !include includes/alert.yaml
input_number: !include includes/input_number.yaml
device_tracker: !include includes/device_tracker.yaml
camera: !include includes/camera.yaml
ios: !include includes/iso.yaml
light: !include includes/light.yaml
input_select: !include includes/input_select.yaml
plant: !include includes/plant.yaml
input_text: !include includes/input_text.yaml
zone: !include includes/zone.yaml


weather:
  - platform: darksky
    api_key: !secret darksky_apikey


notify:
  - platform: ios
    name: mattIphone
    target: '887f840a-462e-3b19-b5de-919e1f1004a7'
  - platform: ios
    name: danniIphone
    target: '409ff712-e1a1-31af-a7a9-b27f61143473'
  - platform: nfandroidtv
    name: Living Room Tv
    host: 192.168.1.30
  - platform: alexa_media
    name: alexa_media

mqtt:
  broker: '192.168.1.253'
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 44
  platform: smart_life

alexa_media:
  accounts:
   - email: !secret alexa_username
     password: !secret alexa_password
     url: "amazon.co.uk"

# emulated_hue:
#   expose_by_default: true
#   exposed_domains:
#     - switch


influxdb:
  host: 192.168.1.253
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0




# recorder:
#   purge_keep_days: 5

octoprint:
  host: 192.168.1.204
  api_key: !secret octoprint_apikey
  bed: true
  number_of_tools: 1 

speedtestdotnet:
  scan_interval:
    minutes: 10
  monitored_conditions:
    - ping
    - download
    - upload


mobile_app:


hacs:
  token: !secret githubtoken


climate:
  - platform: mqtt
    name: bedroom
    modes:
      - "off"
      - "auto"
    power_command_topic: "bedroom/ac/power/set"
    temperature_command_topic: "bedroom/ac/temperature/set"
    min_temp: 18
    max_temp: 30
    current_temperature_topic: "bedroom/senorarray"
    current_temperature_template: "{{ value_json.temperature }}"
    temp_step: 0.5

lovelace:
  mode: yaml

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password
  driving_speed: 18
  interval_seconds: 10
  max_gps_accuracy: 200
  max_update_wait:
    minutes: 45
  show_as_state:
    - driving
    - moving
  warning_threshold: 2
  error_threshold: 3


person:
  - name: Matt
    id: matt
    device_trackers:
      - device_tracker.life360_matt
      - device_tracker.bt_matt_iphone
  - name: Danni
    id: danni
    device_trackers:
      - device_tracker.life360_danni
      - device_tracker.bt_danni_iphone

media_player:
  - platform: androidtv
    host: 192.168.1.216
    name: "Fire Tv"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037


# image_processing:
#   - platform: tensorflow
#     scan_interval: 604800
#     source:
#       - entity_id: camera.office_cam_stills
#     file_out:
#       - "/config/www/tensorflow/{{ camera_entity.split('.')[1] }}_latest.jpg"
#       - "/config/www/tensorflow/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
#     model:
#       graph: /config/tensorflow/model/frozen_inference_graph.pb
#       categories: 
#         - category: person