title: Security
path: security
cards:
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: quick-access-menu 
        variables:
          - name1: Alarm
          - icon1: shield-home
          - path1: alarm
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: '## Security'
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: "##### Camera's"
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.living_room_cam_stills
            title: Camera's  
            aspect_ratio: 16x9
            deep_press: true
            show_state: false
          - !include  ../jimz011/includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.kitchen_cam_stills
            title: Camera's  
            aspect_ratio: 16x9
            deep_press: true
            show_state: false
          - !include  ../jimz011/includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.office_cam_stills
            title: Camera's
            aspect_ratio: 16x9
            camera_view: live
            deep_press: true
            show_state: false
          - !include  ../jimz011/includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.landing_cam_stills
            title: Camera's
            aspect_ratio: 16x9
            camera_view: live
            deep_press: true
            show_state: false
          - !include  ../jimz011/includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: picture-entity
            style: |
              ha-card {
                border-radius: var(--border-radius);
                overflow: hidden;
              }
            entity: camera.back_garden_cam_stills
            title: Camera's
            aspect_ratio: 16x9
            deep_press: true
            camera_view: live
            show_state: false
          - !include  ../jimz011/includes/blank-card.yaml

### The following piece is for tablets only, You can leave this out if not needed.
  - type: custom:state-switch
    entity: user
    states:
      Home Assistant:
        type: vertical-stack
        cards:
          - type: markdown 
            style: |
              ha-card {
                background: none;
                color: white;
                box-shadow: none;
                text-align: end;
                font-size: 45px;
                height: 155px;
              }
            content: '# [[ sensor.time.state ]]'
### End of tablet code.

  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: '##### Doors'
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.font_door
              - name: Font Door
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.bathroom_door
              - name: Bathroom
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.office_door
              - name: Office
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.back_door_sensor
              - name: Back Door
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - !include  ../jimz011/includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: '##### Windows'
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.bedroom_window
              - name: Bedroom
              - icon: door
              - show_last_changed: true
              - tap_action: more-info
              - variable: icon
              - spin: 'mdi:door-open'
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include  ../jimz011/includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: '##### Motion'
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.bathroom_motion_sensor
              - name: Bathroom
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.hallway_motion_sensor
              - name: Hallway
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.kitchen_motion
              - name: Kitchen
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.office_motion
              - name: Office
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - !include  ../jimz011/includes/blank-card.yaml
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: binary_sensor.kitchencam_motion_sensor
              - name: Kitchen Cam
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: input_boolean.motionlivingroom
              - name: Living Room Cam
              - icon: motion-sensor
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - type: custom:button-card
            color_type: blank-card
            aspect_ratio: 1/1
          - !include  ../jimz011/includes/blank-card.yaml
      - type: custom:decluttering-card
        template: header 
        variables:
          - content: '##### Record Clip'
      - type: horizontal-stack
        cards:
          - !include  ../jimz011/includes/blank-card.yaml
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: switch.record_living_room_camera
              - name: Living room
              - icon: camera
              - show_last_changed: true
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: switch.record_kitchen_camera
              - name: Kitchen
              - icon: camera
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: switch.record_hallway_camera
              - name: Hallway
              - icon: camera
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: switch.record_back_garden_camera
              - name: Back Garden
              - icon: camera
              - show_last_changed: true
              - tap_action: more-info
          - type: custom:decluttering-card
            template: button 
            variables:
              - entity: switch.record_office_camera
              - name: Office Cam
              - icon: camera
              - show_last_changed: true
              - tap_action: more-info
          - !include  ../jimz011/includes/blank-card.yaml
      # - type: custom:decluttering-card
      #   template: header 
      #   variables:
      #     - content: '##### Alarms'
      # - type: horizontal-stack
      #   cards:
      #     - !include  ../jimz011/includes/blank-card.yaml
      #     - type: custom:decluttering-card
      #       template: button 
      #       variables:
      #         - entity: binary_sensor.smoke_sensor_158d000287ab41
      #         - name: Rookmelder
      #         - icon: smoke-detector
      #         - show_last_changed: true
      #         - tap_action: more-info
      #     - type: 'custom:button-card'
      #       color_type: blank-card
      #       aspect_ratio: 1/1
      #     - type: 'custom:button-card'
      #       color_type: blank-card
      #       aspect_ratio: 1/1
      #     - !include  ../jimz011/includes/blank-card.yaml
      - !include  ../jimz011/includes/bottom-card.yaml